nasa-jpl/fastcat

doc/fastcat_device_config_parameters.md, example_configs/single/ati_fts_online.yaml, src/CMakeLists.txt, src/jsd/ati_fts.cc, src/jsd/ati_fts.h, src/jsd/ati_fts_offline.cc, src/jsd/ati_fts_offline.h, src/manager.cc, src/manager.h, test/CMakeLists.txt, test/test_cli.cc
Adds ATI EtherCAT FTS to fastcat
Fixes old dependency on JPL internal package `jpl_timer` which was migrated to `jsd/jsd_timer`
=> Add ATI FTS to fastcat

src/jsd/ati_fts.cc
=> ATI FTS bias sign bugfix

CMakeLists.txt, doc/fastcat_device_config_parameters.md, src/fcgen/fastcat_types.yaml, src/jsd/actuator_fsm_helpers.cc
* Opens ActuatorProfPos commands to non-zero `end_velocity`
=> Alex brinkman actuator api update

.doxyfile.in, src/manager.h
=> added manager doxygen documentation

src/jsd/actuator.cc, src/jsd/actuator.h, src/jsd/actuator_fsm_helpers.cc
fixes #5 
Closes #6 
This works as intended on testbed hardware.
=> Modified actuator reset behavior to no longer disengage brakes

src/jsd/actuator.cc, src/manager.cc
Bug fix for certain EGD drive firmware/feedback configuration to fix unexpected position offsets after first power-on
=> Fix saved position offset after startup

doc/fastcat_device_config_parameters.md, src/jsd/el3318.cc, src/jsd/el3318.h
Based upon request, adding fastcat configuration from yaml to enable a selection of TC element.
=> Added el3318 element config

CMakeLists.txt, src/jsd/actuator.cc
Minor patch to improve Actuator reset handling
=> Bugfix act reset

doc/fastcat_device_config_parameters.md, src/fastcat_devices/fts.cc, src/fastcat_devices/fts.h, src/fastcat_devices/virtual_fts.cc, src/fcgen/fastcat_types.yaml, src/jsd/ati_fts.cc, src/jsd/ati_fts.h
For atiFTS
- Changed from magnitude check to per axis check
- Added a flag to turn on/off sensor safety check
- Added a command to toggle sensor safety check on/off
=> Davkim atifts peraxis check

src/fastcat_devices/fts.cc, src/jsd/ati_fts.cc
atifts, fts had a typo, missing bracket to always fault.
=> Added bracket

CMakeLists.txt, doc/fastcat_device_config_parameters.md, src/CMakeLists.txt, src/fcgen/fastcat_types.yaml, src/jsd/ild1900.cc, src/jsd/ild1900.h, src/jsd/ild1900_offline.cc, src/jsd/ild1900_offline.h, src/manager.cc
Summary:
Adds the Fastcat wrapper for the JSD  driver for the Micro-Epsilon
optoNCDT ILD1900 laser sensor which measures distance with high
precision.
Test Plan:
Will perform preliminary testing via a ROS node that communicates with
the sensor.
Reviewers: alex-brinkman, kwehage
=> Adds driver for Micro-Epsilon ILD1900 sensor

CMakeLists.txt
Updates version of JSD to include timestamp in log messages.
=> Updates version of JSD

CMakeLists.txt, src/jsd/actuator.cc, src/manager.cc, test/test_cli.cc
=> clock time fixes

src/fcgen/fastcat_types.yaml, src/jsd/actuator.cc, src/jsd/actuator.h, src/jsd/actuator_fsm_helpers.cc
Summary:
Adds an additional field to Actuator's state to record faults which happen at the Fastcat level such as command limit violations.
Fixes #65
Test Plan:
To be tested on EELS robotic platform by inducing different faults.
=> Improves Actuator's fault reporting

src/jsd/actuator_fsm_helpers.cc
Fixed typo for calling prof_torque command
=> Fixing transitioning to correct state machine state

CMakeLists.txt
Dependency update from jsd version bump
=> Updated jsd dep version

.gitignore, CMakeLists.txt, src/jsd/actuator.cc, src/jsd/actuator.h, src/jsd/actuator_fsm_helpers.cc, src/jsd/actuator_offline.cc, src/jsd/actuator_offline.h, src/jsd/egd.cc, src/jsd/egd.h
- Bumped JSD version to `v0.2.3`
- Added `EgdFault` to purge outgoing commands on fault
- Changed naming due to JSD definition change from egd to elmo
=> Bumped JSD, purging on fault, update to change of egd to elmo

CMakeLists.txt, src/fcgen/fastcat_types.yaml, src/jsd/actuator.cc, src/jsd/actuator.h, src/jsd/gold_actuator.cc, src/jsd/gold_actuator.h, src/jsd/platinum_actuator.cc, src/jsd/platinum_actuator.h, test/test_unit/test_gold_actuator.cc
feat: For a current project, it was necessary to explicitly change egd output pin values. To do this, a wrapper was necessary for the jsd-level function as a fastcat type addition.
=> Feat digital output capability

CMakeLists.txt, src/jsd/actuator.h, src/jsd/platinum_actuator.cc, src/jsd/platinum_actuator.h, test/test_unit/test_trap.cc
Update the product code in the Platinum driver and fix build issues related to renaming of `trap` functions.
=> Updated product code in Platinum driver and fix build issues

CMakeLists.txt
=> bumping up jsd dep

src/fastcat_devices/three_node_thermal_model.cc, src/fastcat_devices/three_node_thermal_model.h
Needed to init the time for the three node thermal model using the time library to avoid incorrect delta t's.
=> fix: needed to init time correctly

src/fastcat_devices/three_node_thermal_model.h
Needed to add this variable to the header file as it is now used for determining which thermal resistance to operate with.
=> fix: needed to add to header file

src/CMakeLists.txt, src/fastcat_devices/three_node_thermal_model.h, src/manager.cc
Needed to add the includes for the el2809 driver to be picked up by higher level FCAT software.
=> Fix include 2809

src/fastcat_devices/three_node_thermal_model.cc
fix: needed to re-shuffle how the if/else was set in the ConfigFromYaml method
=> fix: incorrect if/else sequence found and corrected

src/manager.cc
fix: Mistakenly forgot the EL2809 offline configuration.
=> feat: initial commit

CMakeLists.txt
=> Fix product code is compatible el2809 el1008

CMakeLists.txt
Append to `CMAKE_INSTALL_PREFIX`.
Fixes #138
=> Proposed fix

CMakeLists.txt, src/manager.cc
The threshold was something semi-arbitrary when conceived, so we bumped it up in this PR to allow users more flexibility in its usage.
=> Bump ExplicitInterpolationCyclesDelay threshold

.github/workflows/build.yml, .github/workflows/patch-action.yml, .github/workflows/test.yml
Added patch-action workflow from JSD to fastcat
=> Add workflows to fastcat
