nasa-jpl/fastcat

doc/fastcat_device_config_parameters.md
src/CMakeLists.txt
src/fcgen/fastcat_types.yaml
src/jsd/el4102.cc
src/jsd/el4102.h
src/jsd/el4102_offline.cc
src/jsd/el4102_offline.h
src/manager.cc

Summary:
Adds the Fascat wrapper for the JSD driver of Beckhoff El4102
terminal. This is a 2-channel analog output of voltage range 0-10 V.
Test Plan:
Performed tests via a ROS node that communicates with the terminal.
The outputs were measured with a multimeter.

Adds driver for Beckhoff El4102 analog output

---

src/fcgen/fastcat_types.yaml
src/jsd/egd.cc
src/jsd/egd_offline.cc

Summary:
Extends the EGD Fastcat driver to enable the selection of the
gain scheduling strategy for its controller and the selection of
particular gain sets when the strategy is manual scheduling.
Test Plan:
Tested on a ROS node that communicates with the Elmo
Gold Drive motor controller.

Support gain scheduling in EGD Fastcat driver.

---

doc/fastcat_device_config_parameters.md
src/jsd/actuator.cc
src/jsd/actuator.h
src/jsd/egd.cc
src/jsd/egd.h
src/yaml_parser.cc
src/yaml_parser.h

Summary:
Adds an optional configuration parameter to the egd and actuator's
drivers to allow setting the controller gain scheduling mode before
the EtherCAT device enters operational mode.
Test Plan:
Tested on ROS node communicating with the Elmo motor
controller through the egd and actuator's drivers.

Adds gain scheduling config to driver of EGD and Actuator.

---

src/device_base.h
src/jsd/actuator.cc
src/jsd/actuator.h
src/manager.cc
src/yaml_parser.cc
src/yaml_parser.h

Daniel, mind taking a look over this code to see if you agree with what it does?
EELS is about to test this on the robot, but it is meant to allow an actuator to ignore any value saved to disk and just read position from an absolute encoder at startup.

Added optional flag to respect absolute encoder positions

---

src/jsd/actuator_fsm_helpers.cc

The trap_generate function used for actuator profile position commands (and prof vel) uses actual position and velocity starting point, but this appears to result in profiles that reset back zero velocity.
We've shifted this to use the latest COMMANDED velocity and position as the initial values for the trap profile (as was already suggested in comments in the code), which will hopefully correct the profile position behavior.
Desired behavior: after sending a profiled position command, sending a new one will just update the target setpoint and re profile from the current position and velocity.
Actual behavior: sending a new profile position command appears to reset velocity back to zero, such that sending a stream of profile position commands results in no motion.

Shifted prof trap init to cmd instead of actual

---

src/jsd/actuator_fsm_helpers.cc

We found an issue where using last COMMANDED joint position for profile position commands could cause joints to snap back to their last commanded position if they drifted slightly during operation of other joints (plus at startup last commanded goes back to zero no matter the actual position of the joints.
Solution tested on EELS 1.0 9 module was to use latest ACTUAL position alongside last COMMANDED velocity, which appears to fix both the original problem of 1) velocity constantly resetting back to zero when a stream of profile commands are sent, and the new problem 2) of joints snapping back to last commanded position.

Make profile pos use current position, last cmd velocity

---

src/manager.cc

Sets the EtherCAT cycle period to be the value of the timeout when fetching the EtherCAT frame via the jsd_read function. The underlying SOEM's function, `ecx_receive_processdata` expects the timeout to be in microseconds. The issue was that `Manager::Process` passed a timeout expressed in nanoseconds. Hence, the fix was to express such quantity in microseconds.

Fixes units of jsd_read timeout in Process()

---

doc/fastcat_device_config_parameters.md
src/jsd/actuator.cc
src/jsd/actuator.h
src/jsd/actuator_fsm_helpers.cc

Summary:
Implements an optional hold position functionality in the actuator driver. For profile position commands, after reaching the desired position, the driver actively holds the position until other commands are issued. The functionality can be activated through an optional parameter `prof_pos_hold` in the configuration yaml file. Set to true to activate it.
This functionality is useful for actuators without the brakes. It mimics the engagement of the brakes after a position profile is achieved.
Test Plan:
Tested on an Elmo Gold Whistle connected to a DC motor and manually attempting to rotate the shaft after the profile position is achieved.

Hold position after profile position command in actuator driver

---

src/jsd/actuator.cc

Need to account for actual_velocity being impacted by both gear_ratio *and* motor_encoder_gear_ratio to get an accurate motor speed for power calculation.

Corrected power calc to account for gear ratio

---

src/jsd/actuator.cc

Summary:
The variable faulted in the Actuator's state was not assigned a value. This has been fixed.
Fixes #47

Fixes faulted assignment in Actuator driver

---

CMakeLists.txt
src/fcgen/fastcat_types.yaml
src/fcgen/types.h.cog
src/jsd/actuator.cc
src/jsd/actuator.h
src/jsd/actuator_fsm_helpers.cc
src/jsd/actuator_offline.cc
src/jsd/actuator_offline.h
src/jsd/egd.cc
src/manager.cc
src/manager.h

* Makes use of `servo_enabled` flag in JSD
* Uses actuator fault enum more properly
* Adds check for at least one actuator on the bus before looking for saved pos file (closes #45)

passing servo_enabled through fastcat now, updated to fault code

---

doc/fastcat_device_config_parameters.md
example_configs/one_of_every_device_offline.yaml
src/CMakeLists.txt
src/fastcat_devices/linear_interpolation.cc
src/fastcat_devices/linear_interpolation.h
src/fcgen/fastcat_types.yaml
src/manager.cc
test/test_cli.cc
test/test_unit/CMakeLists.txt
test/test_unit/test_linear_interpolation.cc
test/test_unit/test_linear_interpolation_yamls/invalid_1.yaml
test/test_unit/test_linear_interpolation_yamls/invalid_2.yaml
test/test_unit/test_linear_interpolation_yamls/invalid_3.yaml
test/test_unit/test_linear_interpolation_yamls/invalid_4.yaml
test/test_unit/test_linear_interpolation_yamls/invalid_5.yaml
test/test_unit/test_linear_interpolation_yamls/invalid_6.yaml
test/test_unit/test_linear_interpolation_yamls/invalid_7.yaml
test/test_unit/test_linear_interpolation_yamls/valid_abs.yaml
test/test_unit/test_linear_interpolation_yamls/valid_abs_no_error.yaml
test/test_unit/test_linear_interpolation_yamls/valid_squared.yaml

Adds implementation, test, and documentation for a new Linear Interpolation Fastcat Device
closes #52 
The example updated in `example_config/one_of_every_device_offline.yaml` contains a simple `fabs` interpolation table that observes a sine wave signal and saturates outside the range of `[-9, 9]`. The output of this is shown below:

Add LinearInterpolator Device 

---

example_configs/one_of_every_device_offline.yaml
src/jsd/actuator.cc
src/jsd/actuator.h
src/jsd/actuator_fsm_helpers.cc
src/jsd/actuator_offline.cc
src/jsd/actuator_offline.h
test/test_cli.cc

* Offline Actuator devices will emulate `motor_on` and `servo_enabled` state variables now
* Actuator Prof Pos/Vel/torque commands will now wait until the brakes are disengaged before starting motion.
Closes #55 and #54

Feat improve actuator offline

---

CMakeLists.txt
src/jsd/actuator.cc
src/jsd/actuator.h
src/jsd/actuator_fsm_helpers.cc
src/jsd/actuator_offline.cc
src/jsd/actuator_offline.h

Makes use of the new `jsd_egd_clear_errors` to help reset function work as desired. 
bump minor version

Feat clear error on reset

---

src/trap.c
test/test_unit/CMakeLists.txt
test/test_unit/test_trap.cc

EELS was seeing a problem where commanding new prof_vel setpoints at close to the rate of fastcat would result in zero velocity due to the dt always being 0 and so 0 velocity being sent as t_init was updated.
Added a minimum dt of 0.001s so that the very first cmd_vel will not be zero. For a 1kHz fastcat loop, this just moves one cycle forward in time; also works for anything lower such as 100Hz, just means the vel tracking is slower than normal if you keep updating setpoints at 100Hz.

Add minimum dt to trap_update_vel

---

doc/fastcat_device_config_parameters.md
example_configs/one_of_every_device_offline.yaml
src/fastcat_devices/function.cc
src/fastcat_devices/function.h
src/fastcat_devices/signal_generator.cc
src/fastcat_devices/signal_generator.h
src/manager.cc
src/manager.h

Adds new function blocks:
* Summation block: adds two or more signals together
* Multiplication block: multiplies two or more signals together
* Exponential block: raises a constant to the value of a signal
* Power block: raises a signal to a constant power
* Sigmoid logistic function
Adds new signal generator blocks:
* Uniform random generator
* Gaussian random generator
Closes #10

Add more function and signal generator blocks

---

src/jsd/actuator_fsm_helpers.cc

EELS are sending streams of profile inputs to fastcat because they want continuous control with a finite dwell period, but the recent brake disengage fix added a screen print every time a new profile is received while brakes are already disengaged.
This adds a check to see if the actuator state machine is already set to the incoming profile type and skips the print if so (assumes the operator will have already seen the first time this message prints after receiving the first in a stream of profile commands)

Quiet brake disengage

---

src/jsd/actuator.cc

Elmo actuator was not working correctly(position tracking error when profiled traj is commanded) with loop rate of power of 2.
While converting `target_loop_rate` into `egd` configuration which is INT8 type, round up should be done.
Tested with 128hz, 256hz and working as expected without error.

Round up for actuator loop period

---

src/jsd/actuator_fsm_helpers.cc

When a command(e.g. prof_pos) was invoked with arguments that is out of bound, it gets rejected.
The problem is, argument validation is done after checking actuator SMS, which sends reset command to disengage brake.
Changing order of check up would solve the problem

Changed orders for cmds to not reset when rejecting cmd

---

src/CMakeLists.txt
src/jsd/actuator.h
src/jsd/actuator_offline.h
test/CMakeLists.txt
test/test_unit/CMakeLists.txt
test/test_unit/test_actuator.cc

Added proper `Tester` friend class that can be used to generalize access to protected and private fields/methods in the device class.

Apb ut friend 2

---

doc/fastcat_device_config_parameters.md
src/fastcat_devices/fts.cc
test/test_unit/test_fts.cc
test/test_unit/test_fts_yamls/fts_wide_cal_matrix.yaml

Going through the code, we surmised that calibration matrices with number of signals greater than 6 was not supported. Though the documentation (the previous state of the README), coincides with this, Fts should allow for more than 6 input signals.
These changes give a test that show that with a varying 7th signal, updates are now properly reflected by the UpdateSignals function.

Fix correct signal update

---

src/manager.cc
src/manager.h

As per previous discussion, allow an external source for process time, such as in case of using FastCAT with a non realtime simulation engine.

Add external_time optional argument to Process

---

src/jsd/actuator.h
src/jsd/actuator_fsm_helpers.cc
src/jsd/gold_actuator.cc
src/jsd/platinum_actuator_offline.cc
src/trap.c
src/trap.h

Avoids name collision when using fastcat as an external library together with the "trap" library. 
This is necessary to support composition of arm and fcat nodes into a single executable.

Prefix trap functions with fastcat to support composition

---

CMakeLists.txt

Updates JSD version to 2.3.2 so that the fix implemented in JSD to allow communication in networks with Platinum drives and other devices is incorporated into Fastcat.

Updates the JSD version to bring in Platinum related changes

---

CMakeLists.txt
src/trap.c

Suppress unused variable warnings when setting log level to FATAL or WARNING. 
Depends on https://github.com/nasa-jpl/jsd/pull/97 getting merged and a new semantic tag jsd:v2,.3.7 issued before merging.

Dwai jsd compile time verbosity level

---

CMakeLists.txt
doc/fastcat_device_config_parameters.md
src/fcgen/fastcat_types.yaml
src/jsd/el2809.cc
src/jsd/el2809.h
src/jsd/el2809_offline.cc
src/jsd/el2809_offline.h

This PR adds in the necessary higher-level fastcat software to use the new EL2809 driver for 24V digital output.

Feat el2809 driver addition

---

doc/fastcat_device_config_parameters.md
example_configs/one_of_every_device_offline.yaml
src/fastcat_devices/three_node_thermal_model.cc
src/fastcat_devices/three_node_thermal_model.h
test/test_unit/test_three_node_thermal_model_yamls/invalid_num_signals.yaml
test/test_unit/test_three_node_thermal_model_yamls/invalid_num_temps.yaml
test/test_unit/test_three_node_thermal_model_yamls/valid.yaml

This modification to the thermal model allows one to have separate thermal masses for when the motor is on or off. This is one method of being conservative in estimating the heat-up/ cool-down of the motor.

feat: using different thermal masses for on/off motor states

---

CMakeLists.txt

This bump uses the new version of jsd that resolves the infinite spinning bug.

feat: initial commit

---

CMakeLists.txt
src/jsd/actuator.cc
src/jsd/ati_fts.cc
src/jsd/egd.cc
src/jsd/el1008.cc
src/jsd/el2124.cc
src/jsd/el2809.cc
src/jsd/el3104.cc
src/jsd/el3162.cc
src/jsd/el3202.cc
src/jsd/el3208.cc
src/jsd/el3318.cc
src/jsd/el3602.cc
src/jsd/el4102.cc
src/jsd/gold_actuator.cc
src/jsd/ild1900.cc
src/jsd/jed0101.cc
src/jsd/jed0200.cc
src/jsd/platinum_actuator.cc
src/jsd/platinum_actuator.h
src/jsd/platinum_actuator_offline.cc

Updates Fastcat to accommodate the changes of JSD release v3.0.0 which are not backward compatible.
The changes in JSD consisted in replacing the product code field in driver configurations with a driver type field, and renaming the EPD driver (added `nominal` suffix after `epd`) given that there are now two variations of the driver, nominal and SIL.

Updates Fastcat for JSD release v3.0.0

---

src/fcgen/fastcat_types.yaml
src/jsd/actuator.cc
src/jsd/actuator.h
src/jsd/actuator_fsm_helpers.cc
src/jsd/gold_actuator.cc
src/jsd/platinum_actuator.cc

Summary:
Adds a command to the interface of actuator drivers to modify the maximum time the driver will wait in a Profile Disengaging state before faulting.
This capability is useful, for example, for an actuator that executes a commutation search when the corresponding Elmo drive is first enabled. Commutation searches take considerably longer than the one second previously used as timeout (1 s is the maximum value for the drive's brake disengage parameter BP[2]). The new command allows to temporarily increase the timeout so that the Fastcat driver does not fault during the commutation search.
Test Plan:
Tested on the Walking Arm testbed which has actuators with no hall sensors that require an initial commutation search when they are first commanded to move.
Reviewers: preston-rogers

Adds ability to modify the timeout in Profile Disengaging states

---

src/manager.cc

Fixes indexing issue when processing SDO responses in Fastcat's manager.
Original code could not reach the last slave because the iteration loop did not consider index zero corresponds to the master.

Fixes indexing issue when processing SDO responses

---

src/jsd/platinum_actuator_offline.cc

Explicitly initializes the fault_code member of the internal JSD driver's state.
Test Plan:
Tested by @Bouty92 on local Fastcat deployment.

Fixes initialization bug in Elmo Platinum's offline driver

---

src/device_base.cc
src/device_base.h
src/fastcat_devices/three_node_thermal_model.cc
src/fastcat_devices/three_node_thermal_model.h
src/jsd/gold_actuator_offline.cc
src/jsd/platinum_actuator_offline.cc

Added changes to the platinum and gold drive offline modes to have more accurate velocity calculation.
Before this MR, velocity was calculated using the loop period which may be inaccurate due to jitter. Now the velocity is calculated using the prior process loop time and the current process loop time.

Switching to using last time and current time for velocity calculation

---

.github/workflows/build.yml
.github/workflows/test.yml

- Add libyaml-cpp-dev, libreadline
- Add a step to install cogapp for cog
- Use specific compiler to avoid nuisance 0-struct eerrors
- Remove clang if not using it
- Add setting up GTest in workflow
- Had to add PyYaml for unit tests

Fixes build/test Workflows

---

src/CMakeLists.txt

Ubuntu 24 cogapp is named "cogapp" and not "cog" so this build fails on newer systems.

Switching to finding cog on the system

---

src/manager.cc
src/thread_safe_queue.h

Addresses #134
The underlying issue is that `src/manager.cc fastcat::Manager::WriteCommands()` does the queue check and queue pop as two separate atomic operations instead of as one. This creates a vulnerability where if more than one thread `WriteCommands`, it can lead to undefined behavior.
The fix is to add try_pop which makes an atomic operation out of checking if the queue is empty and popping an element from the queue if it's not empty.

Fix #134 by adding an atomic try_pop and using it in WriteCommands
